main:
- name: Introduction
  pageRef: /
  weight: 10
- name: Concepts
  pageRef: /concepts
  weight: 20
- name: Flavors
  idenitifer: flavors
  weight: 30
- name: hTWOo Core
  parent: Flavors
  url: /htwoo-core/
  weight: 55
- name: hTWOo React
  parent: Flavors
  url: /htwoo-react/
  weight: 36
- name: How To's
  pageRef: '/how-to'
  weight: 40
  params:
    dynamic: true
- name: Samples
  url: https://github.com/n8design/htwoo-samples/
  weight: 45
  params:
    blank: true
- name: Engage on GitHub
  url: https://github.com/n8design/htwoo/
  weight: 47
  params:
    blank: true
- name: Changelogs
  idenitifer: changelog
  weight: 50
- name: hTWOo Core - Change Log
  parent: Changelogs
  pageRef: /changelog/htwoo-core-cl
  weight: 51
- name: hTWOo React - Change Log
  parent: Changelogs
  pageRef: /changelog/htwoo-react-cl
  weight: 52
- name: Supporters
  pageRef: supporters
  weight: 70
# - name: Guidelines
#   pageRef: '/guidelines'
#   weight: 120
#   params:
#     dynamic: true
#     section: guidelines
- name: Case Studies
  pageRef: '/case-studies'
  weight: 70
- name: Code of Conduct
  pageRef: /code-of-conduct
  weight: 90
- name: License
  pageRef: /LICENSE
  weight: 100

footer:
- name: "Footer Nav 1"
  url: https://n8d.at
  target: '_blank'
  params:
    blank: true
- name: "Footer Nav 2"
  url: https://n8d.at
  target: '_blank'
  params:
    blank: true
- name: "Footer Nav 3"
  url: https://n8d.at
  target: '_blank'
  params:
    blank: true
legal:
  - name: "Imprint"
    url: /imprint
    params:
      blank: false
  - name: "About"
    url: https://n8d.at
    params:
      blank: false
  - name: "Contact"
    url: https://n8d.at
    params:
      blank: true