export const lightModeTheme = {
  "themeDarker": "#4b3867",
  "themeDark": "#664b8c",
  "themeDarkAlt": "#7959a5",
  "themePrimary": "#8764b8",
  "themeSecondary": "#9372c0",
  "themeTertiary": "#b29ad4",
  "themeLight": "#d7c9ea",
  "themeLighter": "#e9e2f4",
  "themeLighterAlt": "#f9f8fc",
  "black": "#000000",
  "blackTranslucent40": "rgba(0,0,0,.4)",
  "neutralDark": "#201f1e",
  "neutralPrimary": "#323130",
  "neutralPrimaryAlt": "#3b3a39",
  "neutralSecondary": "#605e5c",
  "neutralSecondaryAlt": "#8a8886",
  "neutralTertiary": "#a19f9d",
  "neutralTertiaryAlt": "#c8c6c4",
  "neutralQuaternary": "#d2d0ce",
  "neutralQuaternaryAlt": "#e1dfdd",
  "neutralLight": "#edebe9",
  "neutralLighter": "#f3f2f1",
  "neutralLighterAlt": "#faf9f8",
  "accent": "#8764b8",
  "white": "#ffffff",
  "whiteTranslucent40": "rgba(255,255,255,.4)",
  "yellowDark": "#d29200",
  "yellow": "#ffb900",
  "yellowLight": "#fff100",
  "orange": "#d83b01",
  "orangeLight": "#ea4300",
  "orangeLighter": "#ff8c00",
  "redDark": "#a4262c",
  "red": "#e81123",
  "magentaDark": "#5c005c",
  "magenta": "#b4009e",
  "magentaLight": "#e3008c",
  "purpleDark": "#32145a",
  "purple": "#5c2d91",
  "purpleLight": "#b4a0ff",
  "blueDark": "#002050",
  "blueMid": "#00188f",
  "blue": "#0078d4",
  "blueLight": "#00bcf2",
  "tealDark": "#004b50",
  "teal": "#008272",
  "tealLight": "#00b294",
  "greenDark": "#004b1c",
  "green": "#107c10",
  "greenLight": "#bad80a",
  "backgroundOverlay": "whitesmoke",
  "themeAccentTranslucent10": "rgba(135, 100, 184, 0.10)",
  "bodyBackground": "whitesmoke",
  "bodyFrameBackground": "whitesmoke",
  "accentButtonText": "#ffffff",
  "buttonBackground": "#ffffff",
  "primaryButtonText": "#ffffff",
  "primaryButtonTextHovered": "#ffffff",
  "primaryButtonTextPressed": "#ffffff",
  "inputBackground": "#ffffff",
  "inputForegroundChecked": "#ffffff",
  "listBackground": "#ffffff",
  "menuBackground": "#ffffff",
  "cardStandoutBackground": "#ffffff",
  "bodyTextChecked": "#000000",
  "buttonTextCheckedHovered": "#000000",
  "link": "#8764b8",
  "primaryButtonBackground": "#8764b8",
  "inputBackgroundChecked": "#8764b8",
  "inputIcon": "#8764b8",
  "inputFocusBorderAlt": "#8764b8",
  "menuIcon": "#8764b8",
  "menuHeader": "#8764b8",
  "accentButtonBackground": "#8764b8",
  "primaryButtonBackgroundPressed": "#664b8c",
  "inputBackgroundCheckedHovered": "#664b8c",
  "inputIconHovered": "#664b8c",
  "linkHovered": "#4b3867",
  "primaryButtonBackgroundHovered": "#7959a5",
  "inputPlaceholderBackgroundChecked": "#e9e2f4",
  "bodyBackgroundChecked": "#edebe9",
  "bodyFrameDivider": "#edebe9",
  "bodyDivider": "#edebe9",
  "variantBorder": "#edebe9",
  "buttonBackgroundCheckedHovered": "#edebe9",
  "buttonBackgroundPressed": "#edebe9",
  "listItemBackgroundChecked": "#edebe9",
  "listHeaderBackgroundPressed": "#edebe9",
  "menuItemBackgroundPressed": "#edebe9",
  "menuItemBackgroundChecked": "#edebe9",
  "bodyBackgroundHovered": "#f3f2f1",
  "buttonBackgroundHovered": "#f3f2f1",
  "buttonBackgroundDisabled": "#f3f2f1",
  "buttonBorderDisabled": "#f3f2f1",
  "primaryButtonBackgroundDisabled": "#f3f2f1",
  "disabledBackground": "#f3f2f1",
  "listItemBackgroundHovered": "#f3f2f1",
  "listHeaderBackgroundHovered": "#f3f2f1",
  "menuItemBackgroundHovered": "#f3f2f1",
  "primaryButtonTextDisabled": "#d2d0ce",
  "disabledSubtext": "#d2d0ce",
  "listItemBackgroundCheckedHovered": "#e1dfdd",
  "disabledBodyText": "#a19f9d",
  "variantBorderHovered": "#a19f9d",
  "buttonTextDisabled": "#a19f9d",
  "inputIconDisabled": "#a19f9d",
  "disabledText": "#a19f9d",
  "bodyText": "#323130",
  "actionLink": "#323130",
  "buttonText": "#323130",
  "inputBorderHovered": "#323130",
  "inputText": "#323130",
  "listText": "#323130",
  "menuItemText": "#323130",
  "bodyStandoutBackground": "#faf9f8",
  "defaultStateBackground": "#faf9f8",
  "actionLinkHovered": "#201f1e",
  "buttonTextHovered": "#201f1e",
  "buttonTextChecked": "#201f1e",
  "buttonTextPressed": "#201f1e",
  "inputTextHovered": "#201f1e",
  "menuItemTextHovered": "#201f1e",
  "bodySubtext": "#605e5c",
  "focusBorder": "#605e5c",
  "inputBorder": "#605e5c",
  "smallInputBorder": "#605e5c",
  "inputPlaceholderText": "#605e5c",
  "buttonBorder": "#8a8886",
  "disabledBodySubtext": "#c8c6c4",
  "disabledBorder": "#c8c6c4",
  "buttonBackgroundChecked": "#c8c6c4",
  "menuDivider": "#c8c6c4",
  "cardShadow": "0 1.6px 3.6px 0 rgba(0, 0, 0, 0.132), 0 0.3px 0.9px 0 rgba(0, 0, 0, 0.108)",
  "cardShadowHovered": "0 0 1px #a19f9d",
  "primaryButtonBorder": "transparent",
  "errorText": "#a4262c",
  "messageText": "#323130",
  "messageLink": "#005A9E",
  "messageLinkHovered": "#004578",
  "infoIcon": "#605e5c",
  "errorIcon": "#A80000",
  "blockingIcon": "#FDE7E9",
  "warningIcon": "#797775",
  "severeWarningIcon": "#D83B01",
  "successIcon": "#107C10",
  "infoBackground": "#f3f2f1",
  "errorBackground": "#FDE7E9",
  "blockingBackground": "#FDE7E9",
  "warningBackground": "#FFF4CE",
  "severeWarningBackground": "#FED9CC",
  "successBackground": "#DFF6DD",
  "warningHighlight": "#ffb900",
  "successText": "#107C10",
  "listTextColor": "#323130",
  "warningText": "#323130",
  "elevation4": "0 1.6px 3.6px 0 rgba(0, 0, 0, 0.132), 0 0.3px 0.9px 0 rgba(0, 0, 0, 0.108)",
  "elevation8": "0 3.2px 7.2px 0 rgba(0, 0, 0, 0.132), 0 0.6px 1.8px 0 rgba(0, 0, 0, 0.108)",
  "elevation16": "0 6.4px 14.4px 0 rgba(0, 0, 0, 0.132), 0 1.2px 3.6px 0 rgba(0, 0, 0, 0.108)",
  "elevation64": "0 25.6px 57.6px 0 rgba(0, 0, 0, 0.22), 0 4.8px 14.4px 0 rgba(0, 0, 0, 0.18)",
  "roundedCorner2": "2px",
  "roundedCorner4": "4px",
  "roundedCorner6": "6px",
  "tinyFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "tinyMozOsxFontSmoothing": "grayscale",
  "tinyWebkitFontSmoothing": "antialiased",
  "tinyFontSize": "10px",
  "tinyFontWeight": 400,
  "xSmallFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "xSmallMozOsxFontSmoothing": "grayscale",
  "xSmallWebkitFontSmoothing": "antialiased",
  "xSmallFontSize": "10px",
  "xSmallFontWeight": 400,
  "smallFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "smallMozOsxFontSmoothing": "grayscale",
  "smallWebkitFontSmoothing": "antialiased",
  "smallFontSize": "12px",
  "smallFontWeight": 400,
  "smallPlusFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "smallPlusMozOsxFontSmoothing": "grayscale",
  "smallPlusWebkitFontSmoothing": "antialiased",
  "smallPlusFontSize": "12px",
  "smallPlusFontWeight": 400,
  "mediumFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "mediumMozOsxFontSmoothing": "grayscale",
  "mediumWebkitFontSmoothing": "antialiased",
  "mediumFontSize": "14px",
  "mediumFontWeight": 400,
  "mediumPlusFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "mediumPlusMozOsxFontSmoothing": "grayscale",
  "mediumPlusWebkitFontSmoothing": "antialiased",
  "mediumPlusFontSize": "16px",
  "mediumPlusFontWeight": 400,
  "largeFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "largeMozOsxFontSmoothing": "grayscale",
  "largeWebkitFontSmoothing": "antialiased",
  "largeFontSize": "18px",
  "largeFontWeight": 400,
  "xLargeFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "xLargeMozOsxFontSmoothing": "grayscale",
  "xLargeWebkitFontSmoothing": "antialiased",
  "xLargeFontSize": "20px",
  "xLargeFontWeight": 600,
  "xLargePlusFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "xLargePlusMozOsxFontSmoothing": "grayscale",
  "xLargePlusWebkitFontSmoothing": "antialiased",
  "xLargePlusFontSize": "24px",
  "xLargePlusFontWeight": 600,
  "xxLargeFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "xxLargeMozOsxFontSmoothing": "grayscale",
  "xxLargeWebkitFontSmoothing": "antialiased",
  "xxLargeFontSize": "28px",
  "xxLargeFontWeight": 600,
  "xxLargePlusFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "xxLargePlusMozOsxFontSmoothing": "grayscale",
  "xxLargePlusWebkitFontSmoothing": "antialiased",
  "xxLargePlusFontSize": "32px",
  "xxLargePlusFontWeight": 600,
  "superLargeFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "superLargeMozOsxFontSmoothing": "grayscale",
  "superLargeWebkitFontSmoothing": "antialiased",
  "superLargeFontSize": "42px",
  "superLargeFontWeight": 600,
  "megaFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "megaMozOsxFontSmoothing": "grayscale",
  "megaWebkitFontSmoothing": "antialiased",
  "megaFontSize": "68px",
  "megaFontWeight": 600
};

export const darkModeTheme = {
  "themeDarker": "#37385d",
  "themeDark": "#4a4c7e",
  "themeDarkAlt": "#585a95",
  "themePrimary": "#6264a7",
  "themeSecondary": "#7173b0",
  "themeTertiary": "#989ac9",
  "themeLight": "#c8c9e4",
  "themeLighter": "#e1e1f1",
  "themeLighterAlt": "#f7f7fb",
  "black": "#f8f8f8",
  "blackTranslucent40": "rgba(0,0,0,.4)",
  "neutralDark": "#f4f4f4",
  "neutralPrimary": "#ffffff",
  "neutralPrimaryAlt": "#dadada",
  "neutralSecondary": "#d0d0d0",
  "neutralSecondaryAlt": "#8a8886",
  "neutralTertiary": "#c8c8c8",
  "neutralTertiaryAlt": "#181818",
  "neutralQuaternary": "#191919",
  "neutralQuaternaryAlt": "#1a1a1a",
  "neutralLight": "#1c1c1c",
  "neutralLighter": "#1d1d1d",
  "neutralLighterAlt": "#1e1e1e",
  "accent": "#6264a7",
  "white": "#1f1f1f",
  "whiteTranslucent40": "rgba(255,255,255,.4)",
  "yellowDark": "#d29200",
  "yellow": "#ffb900",
  "yellowLight": "#fff100",
  "orange": "#d83b01",
  "orangeLight": "#ea4300",
  "orangeLighter": "#ff8c00",
  "redDark": "#a4262c",
  "red": "#e81123",
  "magentaDark": "#5c005c",
  "magenta": "#b4009e",
  "magentaLight": "#e3008c",
  "purpleDark": "#32145a",
  "purple": "#5c2d91",
  "purpleLight": "#b4a0ff",
  "blueDark": "#002050",
  "blueMid": "#00188f",
  "blue": "#0078d4",
  "blueLight": "#00bcf2",
  "tealDark": "#004b50",
  "teal": "#008272",
  "tealLight": "#00b294",
  "greenDark": "#004b1c",
  "green": "#107c10",
  "greenLight": "#bad80a",
  "primaryText": "#ffffff",
  "backgroundOverlay": "",
  "suiteBarBackground": "#6264a7",
  "suiteBarText": "#1f1f1f",
  "suiteBarDisabledText": "#1c1c1c",
  "topBarBackground": "#1c1c1c",
  "topBarText": "#d0d0d0",
  "topBarHoverText": "#ffffff",
  "dialogBorder": "#1d1d1d",
  "backgroundImageUri": "none",
  "bodyBackground": "#1f1f1f",
  "bodyFrameBackground": "#1f1f1f",
  "accentButtonText": "#1f1f1f",
  "buttonBackground": "#1f1f1f",
  "primaryButtonText": "white",
  "primaryButtonTextHovered": "white",
  "primaryButtonTextPressed": "white",
  "inputBackground": "#1f1f1f",
  "inputForegroundChecked": "#1f1f1f",
  "listBackground": "#1f1f1f",
  "menuBackground": "#1f1f1f",
  "cardStandoutBackground": "#1f1f1f",
  "bodyTextChecked": "#f8f8f8",
  "buttonTextCheckedHovered": "#f8f8f8",
  "link": "#6264a7",
  "primaryButtonBackground": "#6264a7",
  "inputBackgroundChecked": "#6264a7",
  "inputIcon": "#6264a7",
  "inputFocusBorderAlt": "#6264a7",
  "menuIcon": "#6264a7",
  "menuHeader": "#6264a7",
  "accentButtonBackground": "#6264a7",
  "primaryButtonBackgroundPressed": "#4a4c7e",
  "inputBackgroundCheckedHovered": "#4a4c7e",
  "inputIconHovered": "#4a4c7e",
  "linkHovered": "#37385d",
  "primaryButtonBackgroundHovered": "#585a95",
  "inputPlaceholderBackgroundChecked": "#e1e1f1",
  "bodyBackgroundChecked": "#1c1c1c",
  "bodyFrameDivider": "#1c1c1c",
  "bodyDivider": "#1c1c1c",
  "variantBorder": "#1c1c1c",
  "buttonBackgroundCheckedHovered": "#1c1c1c",
  "buttonBackgroundPressed": "#1c1c1c",
  "listItemBackgroundChecked": "#1c1c1c",
  "listHeaderBackgroundPressed": "#1c1c1c",
  "menuItemBackgroundPressed": "#1c1c1c",
  "menuItemBackgroundChecked": "#1c1c1c",
  "bodyBackgroundHovered": "#1d1d1d",
  "buttonBackgroundHovered": "#1d1d1d",
  "buttonBackgroundDisabled": "#1d1d1d",
  "buttonBorderDisabled": "#1d1d1d",
  "primaryButtonBackgroundDisabled": "#1d1d1d",
  "disabledBackground": "#1d1d1d",
  "listItemBackgroundHovered": "#1d1d1d",
  "listHeaderBackgroundHovered": "#1d1d1d",
  "menuItemBackgroundHovered": "#1d1d1d",
  "primaryButtonTextDisabled": "#191919",
  "disabledSubtext": "#191919",
  "listItemBackgroundCheckedHovered": "#1a1a1a",
  "disabledBodyText": "#c8c8c8",
  "variantBorderHovered": "#c8c8c8",
  "buttonTextDisabled": "#c8c8c8",
  "inputIconDisabled": "#c8c8c8",
  "disabledText": "#c8c8c8",
  "bodyText": "#ffffff",
  "actionLink": "#ffffff",
  "buttonText": "#ffffff",
  "inputBorderHovered": "#ffffff",
  "inputText": "#ffffff",
  "listText": "#ffffff",
  "menuItemText": "#ffffff",
  "bodyStandoutBackground": "#1e1e1e",
  "defaultStateBackground": "#1e1e1e",
  "actionLinkHovered": "#f4f4f4",
  "buttonTextHovered": "#f4f4f4",
  "buttonTextChecked": "#f4f4f4",
  "buttonTextPressed": "#f4f4f4",
  "inputTextHovered": "#f4f4f4",
  "menuItemTextHovered": "#f4f4f4",
  "bodySubtext": "#d0d0d0",
  "focusBorder": "#d0d0d0",
  "inputBorder": "#d0d0d0",
  "smallInputBorder": "#d0d0d0",
  "inputPlaceholderText": "#d0d0d0",
  "buttonBorder": "#8a8886",
  "disabledBodySubtext": "#181818",
  "disabledBorder": "#181818",
  "buttonBackgroundChecked": "#181818",
  "menuDivider": "#181818",
  "cardShadow": "0 1.6px 3.6px 0 rgba(0, 0, 0, 0.132), 0 0.3px 0.9px 0 rgba(0, 0, 0, 0.108)",
  "cardShadowHovered": "0 0 1px #c8c8c8",
  "primaryButtonBorder": "transparent",
  "errorText": "#F1707B",
  "messageText": "#F3F2F1",
  "messageLink": "#6CB8F6",
  "messageLinkHovered": "#82C7FF",
  "infoIcon": "#C8C6C4",
  "errorIcon": "#F1707B",
  "blockingIcon": "#442726",
  "warningIcon": "#C8C6C4",
  "severeWarningIcon": "#FCE100",
  "successIcon": "#92C353",
  "infoBackground": "#323130",
  "errorBackground": "#442726",
  "blockingBackground": "#442726",
  "warningBackground": "#433519",
  "severeWarningBackground": "#4F2A0F",
  "successBackground": "#393D1B",
  "warningHighlight": "#fff100",
  "successText": "#92c353",
  "listTextColor": "#323130",
  "warningText": "#F3F2F1",
  "elevation4": "0 1.6px 3.6px 0 rgba(0, 0, 0, 0.132), 0 0.3px 0.9px 0 rgba(0, 0, 0, 0.108)",
  "elevation8": "0 3.2px 7.2px 0 rgba(0, 0, 0, 0.132), 0 0.6px 1.8px 0 rgba(0, 0, 0, 0.108)",
  "elevation16": "0 6.4px 14.4px 0 rgba(0, 0, 0, 0.132), 0 1.2px 3.6px 0 rgba(0, 0, 0, 0.108)",
  "elevation64": "0 25.6px 57.6px 0 rgba(0, 0, 0, 0.22), 0 4.8px 14.4px 0 rgba(0, 0, 0, 0.18)",
  "roundedCorner2": "2px",
  "roundedCorner4": "4px",
  "roundedCorner6": "6px",
  "tinyFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "tinyMozOsxFontSmoothing": "grayscale",
  "tinyWebkitFontSmoothing": "antialiased",
  "tinyFontSize": "10px",
  "tinyFontWeight": 400,
  "xSmallFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "xSmallMozOsxFontSmoothing": "grayscale",
  "xSmallWebkitFontSmoothing": "antialiased",
  "xSmallFontSize": "10px",
  "xSmallFontWeight": 400,
  "smallFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "smallMozOsxFontSmoothing": "grayscale",
  "smallWebkitFontSmoothing": "antialiased",
  "smallFontSize": "12px",
  "smallFontWeight": 400,
  "smallPlusFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "smallPlusMozOsxFontSmoothing": "grayscale",
  "smallPlusWebkitFontSmoothing": "antialiased",
  "smallPlusFontSize": "12px",
  "smallPlusFontWeight": 400,
  "mediumFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "mediumMozOsxFontSmoothing": "grayscale",
  "mediumWebkitFontSmoothing": "antialiased",
  "mediumFontSize": "14px",
  "mediumFontWeight": 400,
  "mediumPlusFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "mediumPlusMozOsxFontSmoothing": "grayscale",
  "mediumPlusWebkitFontSmoothing": "antialiased",
  "mediumPlusFontSize": "16px",
  "mediumPlusFontWeight": 400,
  "largeFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "largeMozOsxFontSmoothing": "grayscale",
  "largeWebkitFontSmoothing": "antialiased",
  "largeFontSize": "18px",
  "largeFontWeight": 400,
  "xLargeFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "xLargeMozOsxFontSmoothing": "grayscale",
  "xLargeWebkitFontSmoothing": "antialiased",
  "xLargeFontSize": "20px",
  "xLargeFontWeight": 600,
  "xLargePlusFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "xLargePlusMozOsxFontSmoothing": "grayscale",
  "xLargePlusWebkitFontSmoothing": "antialiased",
  "xLargePlusFontSize": "24px",
  "xLargePlusFontWeight": 600,
  "xxLargeFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "xxLargeMozOsxFontSmoothing": "grayscale",
  "xxLargeWebkitFontSmoothing": "antialiased",
  "xxLargeFontSize": "28px",
  "xxLargeFontWeight": 600,
  "xxLargePlusFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "xxLargePlusMozOsxFontSmoothing": "grayscale",
  "xxLargePlusWebkitFontSmoothing": "antialiased",
  "xxLargePlusFontSize": "32px",
  "xxLargePlusFontWeight": 600,
  "superLargeFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "superLargeMozOsxFontSmoothing": "grayscale",
  "superLargeWebkitFontSmoothing": "antialiased",
  "superLargeFontSize": "42px",
  "superLargeFontWeight": 600,
  "megaFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "megaMozOsxFontSmoothing": "grayscale",
  "megaWebkitFontSmoothing": "antialiased",
  "megaFontSize": "68px",
  "megaFontWeight": 600
};

export const highContrastTheme = {
  "themeDarker": "#ffe092",
  "themeDark": "#ffd56c",
  "themeDarkAlt": "#ffce51",
  "themePrimary": "#ffc83d",
  "themeSecondary": "#e0b036",
  "themeTertiary": "#997825",
  "themeLight": "#4d3c12",
  "themeLighter": "#29200a",
  "themeLighterAlt": "#0a0802",
  "black": "#ffffff",
  "blackTranslucent40": "rgba(255, 255, 255, 0.40)",
  "neutralDark": "#faf9f8",
  "neutralPrimary": "#f3f2f1",
  "neutralPrimaryAlt": "#c8c6c4",
  "neutralSecondary": "#a19f9d",
  "neutralSecondaryAlt": "#8a8886",
  "neutralTertiary": "#797775",
  "neutralTertiaryAlt": "#484644",
  "neutralQuaternary": "#3b3a39",
  "neutralQuaternaryAlt": "#323130",
  "neutralLight": "#292827",
  "neutralLighter": "#252423",
  "neutralLighterAlt": "#201f1e",
  "accent": "#ffc83d",
  "white": "#1b1a19",
  "whiteTranslucent40": "rgba(31, 31, 31, 0.40)",
  "yellowDark": "#d29200",
  "yellow": "#ffb900",
  "yellowLight": "#fff100",
  "orange": "#d83b01",
  "orangeLight": "#ea4300",
  "orangeLighter": "#ff8c00",
  "redDark": "#a4262c",
  "red": "#e81123",
  "magentaDark": "#5c005c",
  "magenta": "#b4009e",
  "magentaLight": "#e3008c",
  "purpleDark": "#32145a",
  "purple": "#5c2d91",
  "purpleLight": "#b4a0ff",
  "blueDark": "#002050",
  "blueMid": "#00188f",
  "blue": "#0078d4",
  "blueLight": "#00bcf2",
  "tealDark": "#004b50",
  "teal": "#008272",
  "tealLight": "#00b294",
  "greenDark": "#004b1c",
  "green": "#107c10",
  "greenLight": "#bad80a",
  "primaryBackground": "#1b1a19",
  "primaryText": "#f3f2f1",
  "HyperlinkActive": "#ffe092",
  "CommandLinksPressed": "#ffe092",
  "NavigationPressed": "#ffe092",
  "EmphasisHoverBorder": "#ffe092",
  "TopBarPressedText": "#ffe092",
  "HeaderNavigationPressedText": "#ffe092",
  "Hyperlinkfollowed": "#ffe092",
  "EmphasisHoverBackground": "#ffd56c",
  "EmphasisBorder": "#ffd56c",
  "AccentText": "#ffc83d",
  "CommandLinksHover": "#ffc83d",
  "RowAccent": "#ffc83d",
  "NavigationAccent": "#ffc83d",
  "NavigationHover": "#ffc83d",
  "EmphasisBackground": "#ffc83d",
  "HeaderNavigationHoverText": "#ffc83d",
  "HeaderNavigationSelectedText": "#ffc83d",
  "SuiteBarBackground": "#ffc83d",
  "Hyperlink": "#ffc83d",
  "ContentAccent1": "#ffc83d",
  "AccentLines": "#e0b036",
  "HeaderAccentLines": "#e0b036",
  "ButtonPressedBorder": "#e0b036",
  "SuiteBarHoverBackground": "#997825",
  "StrongLines": "#4d3c12",
  "HeaderStrongLines": "#4d3c12",
  "SuiteBarHoverText": "#4d3c12",
  "ButtonPressedBackground": "#4d3c12",
  "ButtonHoverBorder": "#4d3c12",
  "ButtonHoverBackground": "#29200a",
  "SelectionBackground": "rgba(77, 60, 18, 0.50)",
  "HoverBackground": "rgba(41, 32, 10, 0.50)",
  "NavigationHoverBackground": "rgba(41, 32, 10, 0.50)",
  "PageBackground": "#1b1a19",
  "EmphasisText": "#1b1a19",
  "SuiteBarText": "#1b1a19",
  "TileText": "#1b1a19",
  "BackgroundOverlay": "rgba(27, 26, 25, 0.85)",
  "HeaderBackground": "rgba(27, 26, 25, 0.85)",
  "FooterBackground": "rgba(27, 26, 25, 0.85)",
  "DisabledBackground": "#201f1e",
  "HeaderDisabledBackground": "#201f1e",
  "ButtonBackground": "#201f1e",
  "ButtonDisabledBackground": "#201f1e",
  "SubtleEmphasisBackground": "#252423",
  "DialogBorder": "#252423",
  "NavigationSelectedBackground": "rgba(41, 40, 39, 0.78)",
  "TopBarBackground": "rgba(41, 40, 39, 0.78)",
  "DisabledLines": "#292827",
  "HeaderDisabledLines": "#292827",
  "ButtonDisabledBorder": "#292827",
  "SuiteBarDisabledText": "#292827",
  "SubtleLines": "#484644",
  "HeaderSubtleLines": "#484644",
  "ButtonGlyphDisabled": "#484644",
  "DisabledText": "#797775",
  "CommandLinksDisabled": "#797775",
  "HeaderDisableText": "#797775",
  "ButtonDisabledText": "#797775",
  "Lines": "#797775",
  "HeaderLines": "#797775",
  "ButtonBorder": "#797775",
  "CommandLinks": "#a19f9d",
  "Navigation": "#a19f9d",
  "SubtleEmphasisText": "#a19f9d",
  "TopBarText": "#a19f9d",
  "HeaderNavigationText": "#a19f9d",
  "ButtonGlyph": "#a19f9d",
  "BodyText": "#ffff01",
  "WebPartHeading": "#f3f2f1",
  "HeaderText": "#f3f2f1",
  "ButtonText": "#f3f2f1",
  "ButtonGlyphActive": "#f3f2f1",
  "TopBarHoverText": "#f3f2f1",
  "StrongBodyText": "#faf9f8",
  "SiteTitle": "#faf9f8",
  "CommandLinksSecondary": "#faf9f8",
  "SubtleEmphasisCommandLinks": "#faf9f8",
  "HeaderSiteTitle": "#faf9f8",
  "TileBackgroundOverlay": "rgba(255, 255, 255, 0.50)",
  "ContentAccent2": "#00485b",
  "ContentAccent3": "#288054",
  "ContentAccent4": "#767956",
  "ContentAccent5": "#ed0033",
  "ContentAccent6": "#682a7a",
  "backgroundOverlay": "rgba(27, 26, 25, 0.85)",
  "cmdbarSelected": "#4f4f4f",
  "cmdbarSelectedHover": "#484848",
  "neutralPrimaryTranslucent50": "rgba(255, 255, 255, 0.50)",
  "error": "#ff0000",
  "errorBackground": "#442726",
  "themeAccent": "#ffc83d",
  "themeAccentTranslucent10": "rgba(255, 200, 61, 0.10)",
  "suiteBarBackground": "#ffc83d",
  "suiteBarText": "#1b1a19",
  "suiteBarDisabledText": "#292827",
  "topBarBackground": "rgba(41, 40, 39, 0.78)",
  "topBarText": "#a19f9d",
  "topBarHoverText": "#f3f2f1",
  "dialogBorder": "#252423",
  "bodyBackground": "#000000",
  "bodyFrameBackground": "#000000",
  "accentButtonText": "#1b1a19",
  "buttonBackground": "#1b1a19",
  "primaryButtonText": "white",
  "primaryButtonTextHovered": "#1b1a19",
  "primaryButtonTextPressed": "#1b1a19",
  "inputBackground": "#1b1a19",
  "inputForegroundChecked": "#1b1a19",
  "listBackground": "#1b1a19",
  "menuBackground": "#1b1a19",
  "cardStandoutBackground": "#1b1a19",
  "bodyTextChecked": "#ffffff",
  "buttonTextCheckedHovered": "#ffffff",
  "link": "#ffc83d",
  "primaryButtonBackground": "#000000",
  "inputBackgroundChecked": "#ffc83d",
  "inputIcon": "#000000",
  "inputFocusBorderAlt": "#ffff01",
  "menuIcon": "#ffc83d",
  "menuHeader": "#ffc83d",
  "accentButtonBackground": "#ffc83d",
  "primaryButtonBackgroundPressed": "#000000",
  "inputBackgroundCheckedHovered": "#ffd56c",
  "inputIconHovered": "#ffd56c",
  "linkHovered": "#ffe092",
  "primaryButtonBackgroundHovered": "#ffff01",
  "inputPlaceholderBackgroundChecked": "#29200a",
  "bodyBackgroundChecked": "#292827",
  "bodyFrameDivider": "#292827",
  "bodyDivider": "#292827",
  "variantBorder": "#292827",
  "buttonBackgroundCheckedHovered": "#292827",
  "buttonBackgroundPressed": "#292827",
  "listItemBackgroundChecked": "#292827",
  "listHeaderBackgroundPressed": "#292827",
  "menuItemBackgroundPressed": "#292827",
  "menuItemBackgroundChecked": "#292827",
  "bodyBackgroundHovered": "#252423",
  "buttonBackgroundHovered": "#1aebff",
  "buttonBackgroundDisabled": "#252423",
  "buttonBorderDisabled": "#252423",
  "primaryButtonBackgroundDisabled": "#252423",
  "disabledBackground": "#252423",
  "listItemBackgroundHovered": "#252423",
  "listHeaderBackgroundHovered": "#252423",
  "menuItemBackgroundHovered": "#252423",
  "primaryButtonTextDisabled": "#3b3a39",
  "disabledSubtext": "#3b3a39",
  "listItemBackgroundCheckedHovered": "#323130",
  "disabledBodyText": "#797775",
  "variantBorderHovered": "#797775",
  "buttonTextDisabled": "#797775",
  "inputIconDisabled": "#797775",
  "disabledText": "#797775",
  "bodyText": "#ffff01",
  "actionLink": "#f3f2f1",
  "buttonText": "#f3f2f1",
  "inputBorderHovered": "#f3f2f1",
  "inputText": "#f3f2f1",
  "listText": "#f3f2f1",
  "menuItemText": "#f3f2f1",
  "bodyStandoutBackground": "#201f1e",
  "defaultStateBackground": "#201f1e",
  "actionLinkHovered": "#faf9f8",
  "buttonTextHovered": "black",
  "buttonTextChecked": "#faf9f8",
  "buttonTextPressed": "#faf9f8",
  "inputTextHovered": "#faf9f8",
  "menuItemTextHovered": "#faf9f8",
  "bodySubtext": "#a19f9d",
  "focusBorder": "#a19f9d",
  "inputBorder": "#a19f9d",
  "smallInputBorder": "#a19f9d",
  "inputPlaceholderText": "#a19f9d",
  "buttonBorder": "white",
  "disabledBodySubtext": "#484644",
  "disabledBorder": "#484644",
  "buttonBackgroundChecked": "#484644",
  "menuDivider": "#484644",
  "cardShadow": "0 1.6px 3.6px 0 rgba(0, 0, 0, 0.132), 0 0.3px 0.9px 0 rgba(0, 0, 0, 0.108)",
  "cardShadowHovered": "0 0 1px #797775",
  "primaryButtonBorder": "transparent",
  "errorText": "#F1707B",
  "messageText": "#F3F2F1",
  "messageLink": "#6CB8F6",
  "messageLinkHovered": "#82C7FF",
  "infoIcon": "#C8C6C4",
  "errorIcon": "#F1707B",
  "blockingIcon": "#442726",
  "warningIcon": "#C8C6C4",
  "severeWarningIcon": "#FCE100",
  "successIcon": "#92C353",
  "infoBackground": "#323130",
  "blockingBackground": "#442726",
  "warningBackground": "#433519",
  "severeWarningBackground": "#4F2A0F",
  "successBackground": "#393D1B",
  "warningHighlight": "#fff100",
  "successText": "#92c353",
  "listTextColor": "#323130",
  "warningText": "#F3F2F1",
  "elevation4": "0 1.6px 3.6px 0 rgba(0, 0, 0, 0.132), 0 0.3px 0.9px 0 rgba(0, 0, 0, 0.108)",
  "elevation8": "0 3.2px 7.2px 0 rgba(0, 0, 0, 0.132), 0 0.6px 1.8px 0 rgba(0, 0, 0, 0.108)",
  "elevation16": "0 6.4px 14.4px 0 rgba(0, 0, 0, 0.132), 0 1.2px 3.6px 0 rgba(0, 0, 0, 0.108)",
  "elevation64": "0 25.6px 57.6px 0 rgba(0, 0, 0, 0.22), 0 4.8px 14.4px 0 rgba(0, 0, 0, 0.18)",
  "roundedCorner2": "2px",
  "roundedCorner4": "4px",
  "roundedCorner6": "6px",
  "tinyFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "tinyMozOsxFontSmoothing": "grayscale",
  "tinyWebkitFontSmoothing": "antialiased",
  "tinyFontSize": "10px",
  "tinyFontWeight": 400,
  "xSmallFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "xSmallMozOsxFontSmoothing": "grayscale",
  "xSmallWebkitFontSmoothing": "antialiased",
  "xSmallFontSize": "10px",
  "xSmallFontWeight": 400,
  "smallFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "smallMozOsxFontSmoothing": "grayscale",
  "smallWebkitFontSmoothing": "antialiased",
  "smallFontSize": "12px",
  "smallFontWeight": 400,
  "smallPlusFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "smallPlusMozOsxFontSmoothing": "grayscale",
  "smallPlusWebkitFontSmoothing": "antialiased",
  "smallPlusFontSize": "12px",
  "smallPlusFontWeight": 400,
  "mediumFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "mediumMozOsxFontSmoothing": "grayscale",
  "mediumWebkitFontSmoothing": "antialiased",
  "mediumFontSize": "14px",
  "mediumFontWeight": 400,
  "mediumPlusFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "mediumPlusMozOsxFontSmoothing": "grayscale",
  "mediumPlusWebkitFontSmoothing": "antialiased",
  "mediumPlusFontSize": "16px",
  "mediumPlusFontWeight": 400,
  "largeFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "largeMozOsxFontSmoothing": "grayscale",
  "largeWebkitFontSmoothing": "antialiased",
  "largeFontSize": "18px",
  "largeFontWeight": 400,
  "xLargeFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "xLargeMozOsxFontSmoothing": "grayscale",
  "xLargeWebkitFontSmoothing": "antialiased",
  "xLargeFontSize": "20px",
  "xLargeFontWeight": 600,
  "xLargePlusFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "xLargePlusMozOsxFontSmoothing": "grayscale",
  "xLargePlusWebkitFontSmoothing": "antialiased",
  "xLargePlusFontSize": "24px",
  "xLargePlusFontWeight": 600,
  "xxLargeFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "xxLargeMozOsxFontSmoothing": "grayscale",
  "xxLargeWebkitFontSmoothing": "antialiased",
  "xxLargeFontSize": "28px",
  "xxLargeFontWeight": 600,
  "xxLargePlusFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "xxLargePlusMozOsxFontSmoothing": "grayscale",
  "xxLargePlusWebkitFontSmoothing": "antialiased",
  "xxLargePlusFontSize": "32px",
  "xxLargePlusFontWeight": 600,
  "superLargeFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "superLargeMozOsxFontSmoothing": "grayscale",
  "superLargeWebkitFontSmoothing": "antialiased",
  "superLargeFontSize": "42px",
  "superLargeFontWeight": 600,
  "megaFontFamily": "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
  "megaMozOsxFontSmoothing": "grayscale",
  "megaWebkitFontSmoothing": "antialiased",
  "megaFontSize": "68px",
  "megaFontWeight": 600
};