/**
 * Report generator - creates markdown reports of pattern changes
 */

import chalk from 'chalk';
import { writeFile } from 'fs/promises';
import type { ComparisonResult, ResolvedConfig } from './types.js';

/**
 * Generates and saves a markdown report of changes
 * @param results - Comparison results
 * @param config - Resolved configuration
 */
export async function generateReport(
    results: ComparisonResult,
    config: ResolvedConfig
): Promise<void> {
    const reportContent = createMarkdownReport(results);

    if (config.dryRun) {
        console.log(chalk.yellow(`[DRY RUN] Would generate report at: ${config.reportPath}`));
        if (config.verbose) {
            console.log(chalk.gray('\n--- Report Preview ---'));
            console.log(reportContent);
            console.log(chalk.gray('--- End Report ---\n'));
        }
        return;
    }

    try {
        await writeFile(config.reportPath, reportContent, 'utf-8');
        console.log(chalk.green(`Report generated: ${config.reportPath}`));
    } catch (error) {
        if (error instanceof Error) {
            console.error(chalk.red(`Error generating report: ${error.message}`));
        }
    }
}

/**
 * Creates markdown-formatted report content
 * @param results - Comparison results
 * @returns Markdown string
 */
function createMarkdownReport(results: ComparisonResult): string {
    const timestamp = new Date().toISOString();
    const sections: string[] = [];

    // Header
    sections.push('# Pattern Export Report\n');
    sections.push(`**Generated:** ${timestamp}\n`);

    // Summary
    sections.push('## Summary\n');
    sections.push(`- **Total Changes:** ${results.differences.length}`);
    sections.push(`- **New Files:** ${results.newPatterns.length}`);
    sections.push(`- **Modified Files:** ${results.modifiedPatterns.length}`);
    sections.push(`- **Removed Files:** ${results.removedPatterns.length}\n`);

    // New files
    if (results.newPatterns.length > 0) {
        sections.push('## New Files\n');
        sections.push('The following files are new and will be added:\n');
        for (const file of results.newPatterns) {
            sections.push(`- \`${file}\``);
        }
        sections.push('');
    }

    // Modified files
    if (results.modifiedPatterns.length > 0) {
        sections.push('## Modified Files\n');
        sections.push('The following files have been modified:\n');
        for (const file of results.modifiedPatterns) {
            sections.push(`- \`${file}\``);
        }
        sections.push('');
    }

    // Removed files
    if (results.removedPatterns.length > 0) {
        sections.push('## Removed Files\n');
        sections.push('The following files were removed from the source:\n');
        for (const file of results.removedPatterns) {
            sections.push(`- \`${file}\``);
        }
        sections.push('');
    }

    // Detailed changes
    if (results.differences.length > 0) {
        sections.push('## Detailed Changes\n');
        sections.push('| File | Type | Status | Source Hash | Export Hash |');
        sections.push('|------|------|--------|-------------|-------------|');

        for (const diff of results.differences) {
            const status = !diff.exportHash ? 'New' : 'Modified';
            const exportHash = diff.exportHash || 'N/A';
            sections.push(`| \`${diff.path}\` | ${diff.type} | ${status} | \`${diff.sourceHash.substring(0, 8)}...\` | \`${exportHash.substring(0, 8)}...\` |`);
        }
        sections.push('');
    }

    // Footer
    sections.push('---');
    sections.push('*Generated by @n8d/htwoo-pattern-export*\n');

    return sections.join('\n');
}

/**
 * Displays a summary of changes to the console
 * @param results - Comparison results
 * @param config - Resolved configuration
 */
export function displaySummary(
    results: ComparisonResult,
    config: ResolvedConfig
): void {
    console.log(chalk.bold('\n📊 Summary:'));

    if (results.differences.length === 0) {
        console.log(chalk.green('✓ No changes detected. All patterns are up to date.'));
        return;
    }

    console.log(chalk.blue(`  Total changes: ${results.differences.length}`));

    if (results.newPatterns.length > 0) {
        console.log(chalk.green(`  ✓ New files: ${results.newPatterns.length}`));
    }

    if (results.modifiedPatterns.length > 0) {
        console.log(chalk.yellow(`  ⚠ Modified files: ${results.modifiedPatterns.length}`));
    }

    if (results.removedPatterns.length > 0) {
        console.log(chalk.red(`  ✗ Removed files: ${results.removedPatterns.length}`));
    }

    if (config.dryRun) {
        console.log(chalk.yellow('\n🔍 Dry run mode - no files were actually modified'));
    } else {
        console.log(chalk.green('\n✓ Export completed successfully'));
    }

    console.log(chalk.gray(`\nFor detailed report, see: ${config.reportPath}\n`));
}
